export const surpriseMePrompts = [
  "Electric Groove - A logo for a DJ that incorporates dynamic shapes and bright colors.",
"Cosmic Rhythms - A logo for a band that features a cosmic or galactic theme, with swirling colors and shapes.",
"Chromatic Visions - A logo for an artist that incorporates vibrant colors and geometric patterns.",
"Golden Waves - A logo for a beach or surf-related brand that features waves and a warm, golden color scheme.",
"Retro Disco - A logo for a dance club or disco-themed event that has a retro, 70s-inspired aesthetic.",
"Neon Nights - A logo for a night club or bar that features bright neon colors and a futuristic feel.",
"Mystical Melodies - A logo for a musician or band that incorporates mystical or spiritual imagery.",
"Dynamic Beats - A logo for a DJ or electronic music producer that features bold, dynamic lines and shapes.",
"Soulful Sounds - A logo for a soul, R&B, or jazz musician that incorporates smooth, flowing shapes and a warm color scheme.",
"Funky Fresh - A logo for a hip hop or rap artist that has a funky, urban feel with bold typography and pops of color.",
"Fluid Forms - A logo for an art collective or gallery that incorporates flowing, abstract shapes.",
"Majestic Mountains - A logo for an outdoor or adventure-related brand that features mountain imagery and a natural color scheme.",
"Urban Nights - A logo for a city-themed event or brand that incorporates bold typography and gritty textures.",
"Serene Spaces - A logo for a yoga or wellness brand that features calming imagery and a soothing color scheme.",
"Enchanted Forest - A logo for a nature-related brand that incorporates forest or tree imagery with a mystical or fantasy feel.",
"Pop Art Popcorn - A logo for a movie theater or cinema that has a playful, pop art-inspired aesthetic.",
"Dapper and Bold - A logo for a fashion brand that features bold typography and clean lines.",
"Playful Pastels - A logo for a children's toy or clothing brand that incorporates soft pastel colors and playful shapes.",
"Sleek and Modern - A logo for a tech or startup company that has a sleek, modern feel with minimalist shapes and bold typography.",
"Vintage Vinyl - A logo for a record store or music shop that incorporates vintage vinyl record imagery with a retro feel.",
"Electric Atmosphere - A background featuring bright, vibrant colors and dynamic shapes to create a high-energy atmosphere.",
"Glittering Lights - A background featuring glittering, twinkling lights or stars to create a magical and dreamy vibe.",
"Underground Vibe - A background featuring gritty, textured surfaces such as concrete or metal to create an edgy and underground feel.",
"Tropical Paradise - A background featuring lush foliage and warm, tropical colors to create a relaxing and exotic atmosphere.",
"Futuristic World - A background featuring sleek, metallic shapes and futuristic design elements to create a high-tech and sci-fi vibe.",
"Dreamy Pastels - A background featuring soft, pastel colors and flowing shapes to create a dreamy and ethereal atmosphere.",
"Urban Nightlife - A background featuring cityscapes or street art to create a modern and urban feel.",
"Vintage Charm - A background featuring retro design elements and vintage textures to create a nostalgic and charming atmosphere.",
"Cosmic Journey - A background featuring galaxy imagery or other celestial elements to create a cosmic and awe-inspiring vibe.",
"Nature's Beauty - A background featuring stunning landscapes or natural scenery to create a serene and tranquil atmosphere.",
"Retro Gaming - A background featuring retro video game graphics or pixelated designs to create a fun and nostalgic atmosphere.",
"Gothic Romance - A background featuring ornate designs and dark, moody colors to create a romantic and Gothic-inspired atmosphere.",
"Magical Wonderland - A background featuring whimsical designs and fantasy elements to create a magical and enchanting vibe.",
"Sunset Glow - A background featuring warm, golden colors and sunset imagery to create a relaxed and peaceful atmosphere.",
"Artistic Flair - A background featuring abstract designs and bold, expressive brushstrokes to create an artistic and creative atmosphere.",
"Elevate Your Game - A graphic that emphasizes the benefits of the company's products or services in helping customers improve or succeed.",
"The Power of Innovation - A graphic that highlights the company's innovative approach and showcases its cutting-edge technology or unique solutions.",
"Join the Revolution - A graphic that promotes the company as a game-changer and encourages customers to join its movement or embrace its vision.",
"Simplify Your Life - A graphic that highlights the company's products or services as easy and convenient solutions that can simplify customers' lives.",
"Stay Ahead of the Curve - A graphic that emphasizes the company's expertise and experience in a particular industry or field and positions it as a leader.",
"Trust in Our Expertise - A graphic that showcases the company's credentials, experience, and satisfied customers to build trust and credibility.",
"A Better Way to Work - A graphic that promotes the company's products or services as efficient, productive, and effective solutions for businesses and professionals.",
"Get More for Less - A graphic that emphasizes the value of the company's products or services and positions them as affordable and cost-effective.",
"Transform Your Home - A graphic that showcases the company's products or services as transformative and able to improve customers' living spaces.",
"Innovative Solutions for Every Industry - A graphic that highlights the company's versatility and ability to provide unique solutions across a range of industries.",
"Join the Green Revolution - A graphic that promotes the company's commitment to sustainability and encourages customers to choose environmentally friendly products or services.",
"Solutions for Every Need - A graphic that showcases the company's range of products or services and highlights its ability to meet a variety of customer needs.",
"Experience the Difference - A graphic that emphasizes the company's superior quality and positions it as a premium or luxury brand.",
"Get Inspired - A graphic that showcases the company's creativity and encourages customers to explore its products or services for inspiration.",
"Satisfy Your Cravings - A graphic that promotes the company's products or services as indulgent or satisfying treats and encourages customers to indulge in them.",
];
