import React, { useState, useEffect } from 'react'
import { ImageCard } from '../components'

const Home = () => {
    return (
        <section className='max-w-7xl mx-auto'>
            <div>
                <h2 className='font-extrabold text-[#253031] text-[32px]'>Community Feed</h2>
                <p className='mt-2 text-[#279af1] text-[16px]'>View stunning images from other users generated by DALL-E AI</p>
            </div>
        </section>
    )
}

export default Home